"""
Django settings for mofa project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

from easy_thumbnails.conf import Settings as thumbnail_settings


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tk_tpw__$4b$6u0m9u2#btrgl4!ys-qza+%i+**gn=8%lm5)rl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

ADMINS = (
    ('Eugenia', 'eugenia@mofamofamofa.com'),
)


# Application definition

INSTALLED_APPS = (
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pipeline',
    'taggit',
    'django_extensions',
    'rest_framework',
    'adminsortable',
    'filer',
    'easy_thumbnails',
    'image_cropping',
    'ckeditor',
    'django_filters',
    'mptt',
    'paintstore',

    'users',
    'events',
    'galleries',
    'mofa',
    'shop',
    'orders',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'orders.middleware.OrderMiddleware',
    #'mobile_redirect.middleware.MobileRedirectMiddleware',
)

#MOBILE_REDIRECT_URL = 'http://localhost:8000/mobile/'

ROOT_URLCONF = 'mofa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'mofa.context_processors.settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'mofa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mofa_volit',
        'USER': 'mofa_django',
        'PASSWORD': '$imple1234!'
    }
}

DEFAULT_FROM_EMAIL = 'eugenia@mofamofamofa.com'
RECEIVER_EMAIL = 'eugenia@mofamofamofa.com'

#EMAIL_BACKEND = 'django_mandrill.mail.backends.mandrillbackend.EmailBackend'
#MANDRILL_API_KEY = 'Op9qtaezpLG5j0lqryWHwA'
EMAIL_BACKEND = 'sgbackend.SendGridBackend'
SENDGRID_API_KEY = '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'

EMAIL_SUBJECT_PREFIX = '[MOFA]'
SERVER_EMAIL = 'info@simplesolutionsfs.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 2525
EMAIL_USE_TLS = False
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'eugenia@mofamofamofa.com'
SERVER_EMAIL = ''

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'EST'

USE_I18N = False

USE_L10N = False

USE_TZ = False

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')

STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'pipeline.finders.PipelineFinder',
)

AUTH_USER_MODEL = 'users.User'

PIPELINE_CSS = {
    'master': {
        'source_filenames': (
            'css/nanoscroller.css',
            # 'css/hover.css',
            'css/master.less',
        ),
        'output_filename': 'css/master.css'
    },
}

PIPELINE_JS = {
    'base': {
        'source_filenames': (
            'js/jquery.min.js',
            'js/underscore.min.js',
            # 'js/jquery.nanoscroller.js',
            'js/bootstrap/carousel.js',
            # 'js/angular/angular.js',
            # 'js/rotate.js',
            'js/master.js',
            'js/animations.js',
        ),
        'output_filename': 'js/base.js'
    },
    'app': {
        'source_filenames': (
            'js/jquery.min.js',
            'js/jquery.zoom.min.js',
            'js/underscore.min.js',
            'js/jquery.nanoscroller.js',
            'js/bootstrap/carousel.js',
            'js/bootstrap/tooltip.js',
            'js/angular/angular.js',
            'js/angular/angular-route.js',
            'js/angular/angular-resource.js',
            'js/angular/angular-animate.js',
            'js/angular/angular-sanitize.js',
            'js/angular/angular-messages.js',

            'app/controllers/*',
            'app/libs/*',
            'app/templates/*.html',
            'app/templates/**/*.html',
            'app/templates/**/**/*.html',

            'app/app.js',
            'js/master.js',
            'js/animations.js',
        ),
        'output_filename': 'js/app.js'
    }
}

PIPELINE_COMPILERS = (
    'pipeline.compilers.less.LessCompiler',
)

# PIPELINE_LESS_ARGUMENTS = '--source-'

PIPELINE_TEMPLATE_NAMESPACE = 'window.TEMPLATE_CACHE'
PIPELINE_TEMPLATE_FUNC = 'window.template'
PIPELINE_TEMPLATE_SEPARATOR = '/'
PIPELINE_TEMPLATE_EXT = '.html'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.DjangoFilterBackend',
    )
}

THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

CKEDITOR_UPLOAD_PATH = 'ckeditor/'

CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'height': 300,
        'width': '100%',
        'removePlugins': 'stylesheetparser',
        'extraAllowedContent': 'iframe[*]',
    },
}

# CKEDITOR_CONFIGS = {
#     'default': {
#         # 'toolbar': 'Basic',
#     }
# }

# Django Suit configuration example
SUIT_CONFIG = {
    # header
    'ADMIN_NAME': 'MOFA Admin',
    # 'HEADER_DATE_FORMAT': 'l, j. F Y',
    # 'HEADER_TIME_FORMAT': 'H:i',

    # forms
    # 'SHOW_REQUIRED_ASTERISK': True,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': True, # Default True

    # menu
    # 'SEARCH_URL': '/admin/auth/user/',
    # 'MENU_ICONS': {
    #    'sites': 'icon-leaf',
    #    'auth': 'icon-lock',
    # },
    # 'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        {'label': 'General', 'app': 'mofa'},
        'users',
        'orders',
        'shop',
        'galleries',
        'events',
        'filer',

        # 'sites',
        # {'app': 'auth', 'icon':'icon-lock', 'models': ('user', 'group')},
        # {'label': 'Settings', 'icon':'icon-cog', 'models': ('auth.user', 'auth.group')},
        # {'label': 'Support', 'icon':'icon-question-sign', 'url': '/support/'},
    ),

    # misc
    # 'LIST_PER_PAGE': 15
}

AUTHORIZE_API_LOGIN_ID = '24Vc2p6G6Ds'
AUTHORIZE_TRANSACTION_KEY = '6cgRS8284hXW2de7'

TAX_VALUE = 7.5

try:
    from .local_settings import *
except ImportError:
    pass
